FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3-pip python3-dev ffmpeg git \
    && apt-get clean

WORKDIR /app
COPY main.py /app

RUN pip install --no-cache-dir --break-system-packages \
    fastapi \
    uvicorn[standard] \
    git+https://github.com/openai/whisper.git \
    transformers \
    torch==2.7.1+cu128 \
    torchvision==0.22.1+cu128 \
    torchaudio==2.7.1+cu128 \
    --extra-index-url https://download.pytorch.org/whl/cu128

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
