# Dockerfile para apenas CPU

FROM python:3.13-slim

# Evita prompts interativos
ENV DEBIAN_FRONTEND=noninteractive

# Instala dependências básicas e ffmpeg
RUN apt-get update && apt-get install -y \
    ffmpeg \
    git \
    && apt-get clean

# Cria diretório para a app
WORKDIR /app

# Copia arquivos do projeto
COPY . /app

# Instala dependências do projeto
RUN pip install --no-cache-dir --break-system-packages \
    fastapi \
    uvicorn[standard] \
    git+https://github.com/openai/whisper.git \
    transformers \
    torch \
    torchvision \
    torchaudio \
    --extra-index-url https://download.pytorch.org/whl/cpu

# Expõe a porta da API
EXPOSE 8000

# Comando para iniciar a aplicação
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
